### ISSUE TITLE
Support for release bundle permissions

### ISSUE THREAD

**Issue by kdaix** [jfrog/terraform-provider-distribution#1]
**Is your feature request related to a problem? Please describe.**
It is not possible yet to configure release bundle permissions. The feature is really valuable for JFrog Distribution users.

**Describe the solution you'd like**
Release bundle permissions can be configured with `release_bundle` block of `artifactory_permission_target` resource. User can specify include/exclude name patterns, list of the storage repositoritories and actions.
In addition to common read/write/annotate/delete/manage permissions, it's possible to specify release bundle specific `distribute` permission.

**Describe alternatives you've considered**
It does not seem there is a comparable alternative.

**Additional context**

**Comment by martinm82** [comment]
Release bundle support has been added in this PR: https://github.com/jfrog/terraform-provider-artifactory/pull/454.

**Comment by martinm82** [comment]
Regarding defining distribution permissions: From UI perspective the permission targets are configured next to repo, build and release bundles. It would feel more natural to define them as well in the permission_target resource of the Artifactory provider.

But since it is a separate API it indeed would make sense to implement it in a separate provider.

**Comment by alexhung** [comment]
@kdaix @martinm82 Release bundle permission is in [`platform_permission` resource](https://registry.terraform.io/providers/jfrog/platform/latest/docs/resources/permission).
